# Generated by Django 3.2.3 on 2023-08-25 08:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата производства')),
            ],
        ),
        migrations.CreateModel(
            name='CarBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='Тип кузова')),
                ('color', models.CharField(max_length=150, verbose_name='Цвет кузова')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('vin_code', models.CharField(max_length=150, verbose_name='VIN код кузова')),
            ],
            options={
                'verbose_name': 'Кузов',
                'verbose_name_plural': 'Кузова',
                'ordering': ('type',),
            },
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Деталь')),
                ('manufacturer_country', models.CharField(max_length=150, verbose_name='Страна производитель')),
            ],
            options={
                'verbose_name': 'Деталь',
                'verbose_name_plural': 'Детали',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CarComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Количество деталей не может быть меньше 1'), django.core.validators.MaxValueValidator(32767, message='Количество деталей не может быть больше 32767')], verbose_name='Количество деталей')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='api.car', verbose_name='Автомобиль')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='api.components', verbose_name='Деталь')),
            ],
            options={
                'verbose_name': 'Комплектация',
                'verbose_name_plural': 'Комплектации',
                'ordering': ('car',),
            },
        ),
        migrations.AddField(
            model_name='car',
            name='car_body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='api.carbody', verbose_name='Кузов'),
        ),
    ]
