# Generated by Django 3.2.3 on 2023-08-25 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carcomponents',
            name='car',
        ),
        migrations.RemoveField(
            model_name='carcomponents',
            name='component',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='CarBody',
        ),
        migrations.DeleteModel(
            name='CarComponents',
        ),
        migrations.DeleteModel(
            name='Components',
        ),
    ]
