services:

  backend:
    build:
      context: /backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    env_file: ./backend/manufacture/.env
    ports:
      - "5432:5432"