version: '3.3'

volumes:
  pg_data:


services:

  backend:
    build:
      context: /backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    env_file: ./backend/manufacture/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  celery:
    build:
      context: /backend
    hostname: celery
    entrypoint: celery
    command: -A manufacture.celery.app worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - database
      - redis
    links:
      - redis